services:
  drohnenwetter-app:
    build:
      context: ./go
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=8080
      - TEMPLATE_DIR=/app/templates
      - STATIC_DIR=/app/static
    networks:
      - drohnenwetter-net
    deploy:
      replicas: 3
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - drohnenwetter-app
    networks:
      - drohnenwetter-net
    restart: always
networks:
  drohnenwetter-net:
    driver: bridge
